# Generated by Django 5.1.6 on 2025-02-14 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='pause_time',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='resume_time',
        ),
        migrations.CreateModel(
            name='WorkPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_time', models.DateTimeField()),
                ('resume_time', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='backend.worksession')),
            ],
        ),
    ]
