# Generated by Django 5.1.6 on 2025-02-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_worksession_pause_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='resume_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WorkPause',
        ),
    ]
