# Generated by Django 5.1.6 on 2025-02-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_worksession_pause_time_worksession_resume_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_time', models.DateTimeField()),
                ('resume_time', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='backend.worksession')),
            ],
        ),
    ]
